### ISSUE TITLE
expand file extensions supported

### ISSUE THREAD

**Issue by buffetboy2001** [swils/vscode-markdown-scripture#7]
Hi, 

I love the potential of this extension -- thanks for building it! I'll admit that it's only part of what I was hoping for when I went searching for a vscode extension to handle scripture citations. I do have the extension working according to your provided examples; thanks for the good documentation.

I use Quarto for vscode for a lot of my markdown documents, rendering them to PDF or HTML as needed. Quarto req's a `.qmd` file extension in order to work. But in a lot of other ways, it's still a markdown document before it gets rendered. What I noticed was that this vscode extension does not work for any file extension other than `.md`. And I couldn't find a way to modify settings to change that behavior. Is there a way?

**Comment by swils** [comment]
Thanks for using the extension, I love to hear from users :-)

Like so many other Markdown extensions, Scripture hooks into VSCode's [internal Markdown preview](https://code.visualstudio.com/api/extension-guides/markdown-extension).

I looked quickly at the [Quarto extension](https://github.com/quarto-dev/quarto-vscode) and I think it uses a separate instance of the MarkdownIt renderer, with its own internal set of plugins. I don't see a way of making these two extensions work together without changes to _both_. Same for the [Markdown PDF exporter](https://github.com/yzane/vscode-markdown-pdf) extension.

On the other hand, I just tried exporting to HTML using the commonly used Markdown [All-in-One extension](https://github.com/yzhang-gh/vscode-markdown) and this does work well together with Scripture. The reason is that the All-in-One extension also uses the Markdown renderer internal to VSCode. Maybe that can help you?

Don't hesitate to ask any follow up questions.

(As a sidenote: I'm still actively using this extension myself, quite a lot in fact. Time is scarce right now but I do try to keep working on improvements. For starters, I'd love to bundle Sword to make it easier to install translations. But this is proving rather hard to do in an OS-independent way, because Sword is a C++ project and links to libcurl. Other things I'd love to have myself are autocompletion and/or searching, customisable referencing and customisable reference rendering.)

**Comment by buffetboy2001** [comment]
👍 Thanks for the response. I'll keep playing around and see how I can integrate this into my workflow. BTW, it took a bit of effort (learning), but I was able to figure out how to connect & control multiple sources. I think that's a super great feature and it'd be nice to make that easier to make work.
